serverAddr = "192.168.209.151"
serverPort = 7000

auth.method = "token"
auth.token = "pass123456"

[[proxies]]
name = "socks5"
type = "tcp"
localPort = 22
remotePort = 6000

[proxies.plugin]
type = "socks5"